spring:
  datasource:
    druid:
      db0:
        url: jdbc:mysql://120.79.150.74:3306/ds0?characterEncoding=utf-8
        username: root
        password: uAiqwVwjJ8-i
        driver-class-name: com.mysql.jdbc.Driver
      db1:
        url: jdbc:mysql://120.24.80.15:3306/ds1?characterEncoding=utf-8
        username: root
        password: Shiyi123456
        driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-active: 20
    min-idle: 5
    max-wait: 60000
    validation-query: select 1
    validation-query-timeout: 30
    test-while-idle: true
    keep-alive: true
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    test-on-borrow: true
    test-on-return: false
    min-evictable-idle-time-millis: 3600000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 300000
    remove-abandoned: true #是否自动回收超时连接
    remove-abandoned-timeout: 180 #超时时间(以秒数为单位)

mybatis-plus:
  mapper-locations: classpath:/com/ml/**/*Mapper.xml
  typeAliasesPackage: com.ml.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    map-underscore-to-camel-case: false
    default-executor-type: REUSE
    default-statement-timeout: 50000